### ISSUE TITLE
How to Fetch Finale Inventory Item and Report Data

### ISSUE THREAD

**Issue by ratansinghgit** [ni/FINALE#22]
Hi,

I have fetch Inventory Item but it's huge data coming from server, so is there any limit parameter so can I pass and pull the data please help me out this

and For Report data I am using this API
"https://app.finaleinventory.com/patsliquor/doc/report/pivotTable/1411538143436/Report.csv?format=csv&data=product&rowDimensions=productProductId_86%7CproductDescription_133%7CproductCategory_72%7CproductManufacturer_72%7CproductStdBinId_43__U3RkXG5iaW4gSUQ%3D%7CproductStdPacking_43__U3RkXG5wYWNraW5n&metrics=productStockQuantityOnHandUnitsSum_54__VW5pdHNcblFvSA%3D%3D%7CproductStockReservationsUnitsSum_54__VW5pdHNcblJlc2VydmVk%7CproductStockRemainingAfterReservationsUnitsSum_54__VW5pdHNcblJlbWFpbmluZw%3D%3D%7CproductStockOnOrderUnitsSum_54__VW5pdHNcbk9uIG9yZGVy%7CproductStockAvailableToPromiseUnitsSum_54__VW5pdHNcbkF2YWlsYWJsZQ%3D%3D&filters=W1sicHJvZHVjdFN0YXR1cyIsWyJQUk9EVUNUX0FDVElWRSJdXSxbInByb2R1Y3RDYXRlZ29yeSIsbnVsbF0sWyJwcm9kdWN0TWFudWZhY3R1cmVyIixudWxsXSxbInByb2R1Y3RTdGRCaW5JZCIsbnVsbF0sWyJwcm9kdWN0UHJvZHVjdFVybCIsbnVsbF1d&reportTitle=Stock+for+each+product%2C+in+units"
but data is not is correct format 

Thanks

**Comment by pratheekshasn** [comment]
This project does not have anything do with [this](https://www.finaleinventory.com/) Finale Inventory, if that was what your question was about.
